### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by anbilly19** [abdeladim-s/tensorboard_plugin_customizable_plots#9]
Following error appears when clicked on the "customizable plots tab" after successful server initialization.

```
E0913 11:26:42.467386 139851626170112 _internal.py:113] Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib/python3.6/dist-packages/tensorboard/backend/application.py", line 563, in __call__
    return self._app(environ, start_response)
  File "/usr/local/lib/python3.6/dist-packages/tensorboard/backend/application.py", line 155, in wrapper
    return wsgi_app(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorboard/backend/security_validator.py", line 82, in __call__
    return self._application(environ, start_response_proxy)
  File "/usr/local/lib/python3.6/dist-packages/tensorboard/backend/path_prefix.py", line 71, in __call__
    return self._application(environ, start_response)
  File "/usr/local/lib/python3.6/dist-packages/tensorboard/backend/experiment_id.py", line 76, in __call__
    return self._application(environ, start_response)
  File "/usr/local/lib/python3.6/dist-packages/tensorboard/backend/empty_path_redirect.py", line 47, in __call__
    return self._application(environ, start_response)
  File "/usr/local/lib/python3.6/dist-packages/tensorboard/backend/application.py", line 586, in _route_request
    return self.exact_routes[clean_path](environ, start_response)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/wrappers/base_request.py", line 238, in application
    resp = f(*args[:-2] + (request,))
  File "/usr/local/lib/python3.6/dist-packages/tensorboard_plugin_customizable_plots/plugin.py", line 144, in _serve_runs
    ctx = plugin_util.context(request.environ)
AttributeError: module 'tensorboard.plugin_util' has no attribute 'context'
```

**Comment by absadiki** [comment]
@anbilly19, It seems like you have an issue with your tensorboard installation, make sure you installed tensorflow first and then tensorboard 
Could you please follow the advices from [this thread](https://github.com/tensorflow/tensorboard/issues/1724): 

> I got it working with the following steps:
> 
> 1. `pip uninstall tensorflow`
> 2. `pip uninstall tensorboard`
> 3. go to site-packages and remove tensorflow/tensorboard folders
> 4. Reinstalled tensorflow - `pip install [whatever wheel package]`
> 
> You can find the wheel packages here for specific install types: https://www.tensorflow.org/install/pip
> 
> Note: I only stated the specific wheel package because that's what I did.
> 
> I know this doesn't explain the 'why' of the issue but it got things going for me. Hope it helps!

Or go over the thread and try the other suggestions!
